Gymbokning/Controllers/GymClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gymbokning.Data;
using Gymbokning.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Gymbokning.Models.ViewModels;
using AutoMapper;

namespace Gymbokning.Controllers
{
    public class GymClassesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        public GymClassesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IMapper mapper)
        {
            _context = context;
            _userManager = userManager;
            this.mapper = mapper;
        }

        // GET: GymClasses
        public async Task<IActionResult> Index(bool showHistory, bool hasBooking)
        {
            var retGymClassesVM = new IndexViewModel();

            retGymClassesVM.GymClasses = await mapper.ProjectTo<IndexGymClassViewModel>(_context.GymClass
                .AsNoTracking()
                .Include(g => g.ApplicationUserGymClasses)
                .WhereIf(!showHistory, g => g.StartTime > DateTime.Now)
                .WhereIf(hasBooking, g => g.ApplicationUserGymClasses.Count > 0)
                ).ToListAsync();
            retGymClassesVM.ShowHistory = showHistory;
            retGymClassesVM.HasBooking = hasBooking;
            return View(retGymClassesVM);
        }

        [Authorize]
        public async Task<IActionResult> BookingToggle(int? id, bool showHistory, bool hasBooking)
        {
            if (id == null)
                return BadRequest();

            var loggedInUser = await _userManager.GetUserAsync(HttpContext.User);
            if (loggedInUser == null)
                return NotFound();

            var SelectedGymClassForLoggedInUser = await _context.ApplicationUserGymClass
                .AsTracking()
                .Include(ugc => ugc.ApplicationUser)
                .Include(ugc => ugc.GymClass)
                .Where(ugc => ugc.ApplicationUser.Id == loggedInUser.Id && ugc.GymClass.Id == id)
                .ToListAsync();

            //has user not attended? then add user to that gymClass a.k.a. new row in junction-table ApplicationUserGymClass, else remove all rows in junction-table ApplicationUserGymClass
            if (SelectedGymClassForLoggedInUser.Count == 0)
                _context.Add(new ApplicationUserGymClass() { ApplicationUserId = loggedInUser.Id, GymClassId = id.GetValueOrDefault()! });
            else
                _context.ApplicationUserGymClass.RemoveRange(SelectedGymClassForLoggedInUser);
            
            await _context.SaveChangesAsync();

            var routeValues = new RouteValueDictionary {
              { "showHistory", showHistory },
              { "hasBooking", hasBooking }
            };
            return RedirectToAction(nameof(Index), routeValues);
        }

        // GET: GymClasses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return BadRequest();

            var gymClass = await mapper.ProjectTo<GymClassDetailsViewModel>(_context.GymClass.AsNoTracking().Where(m => m.Id == id)).FirstOrDefaultAsync();

            if (gymClass == null)
                return NotFound();

            return View(gymClass);
        }

        // GET: GymClasses/Create
        [Authorize(Roles = RoleNames.AdminRole)]
        public IActionResult Create() => View();

        // POST: GymClasses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = RoleNames.AdminRole)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,StartTime,Duration,Description")] GymClass gymClass)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gymClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gymClass);
        }

        // GET: GymClasses/Edit/5
        [Authorize(Roles = RoleNames.AdminRole)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return BadRequest();

            var gymClass = await _context.GymClass.FindAsync(id);
            if (gymClass == null)
                return NotFound();

            return View(gymClass);
        }

        // POST: GymClasses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = RoleNames.AdminRole)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,StartTime,Duration,Description")] GymClass gymClass)
        {
            if (id != gymClass.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gymClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GymClassExists(gymClass.Id))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gymClass);
        }

        // GET: GymClasses/Delete/5
        [Authorize(Roles = RoleNames.AdminRole)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();

            var gymClass = await _context.GymClass
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gymClass == null)
                return NotFound();

            return View(gymClass);
        }

        // POST: GymClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = RoleNames.AdminRole)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gymClass = await _context.GymClass.FindAsync(id);
            if (gymClass != null)
                _context.GymClass.Remove(gymClass);
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GymClassExists(int id) => (_context.GymClass?.Any(e => e.Id == id)).GetValueOrDefault();
    }
}

Gymbokning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gymbokning</title>
    @*
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        *@
        <link href="~/css/bootstrap.custom.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gymbokning.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="GymClasses" asp-action="Index">Gymbokning</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-secondary" asp-area="" asp-controller="GymClasses" asp-action="Index">Kommande</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-secondary" asp-area="" asp-controller="GymClasses" asp-route-hasbooking="true" asp-action="Index">Bokade pass</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-secondary" asp-area="" asp-controller="GymClasses" asp-route-hasbooking="true" asp-route-showhistory="true" asp-action="Index">Historiska</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @*&copy; 2022 - Gymbokning - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>